// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideShare.Api.Data;

#nullable disable

namespace RideShare.Api.Migrations
{
    [DbContext(typeof(RideShareDbContext))]
    [Migration("20260406163951_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideShare.Core.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("SenderId");

                    b.HasIndex("RideId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RideShare.Core.Entities.OnDemandRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AcceptedRiderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("DropoffLat")
                        .HasColumnType("double precision");

                    b.Property<double>("DropoffLng")
                        .HasColumnType("double precision");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<double>("PickupLat")
                        .HasColumnType("double precision");

                    b.Property<double>("PickupLng")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("RequestedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RideId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedRiderId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RideId");

                    b.HasIndex("Status");

                    b.ToTable("OnDemandRequests");
                });

            modelBuilder.Entity("RideShare.Core.Entities.PricingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseFare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximumFare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MinimumFare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PerKmRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PlatformFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("PricingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseFare = 20.00m,
                            Currency = "PHP",
                            CurrencySymbol = "₱",
                            IsEnabled = true,
                            MaximumFare = 500.00m,
                            MinimumFare = 25.00m,
                            PerKmRate = 5.00m,
                            PlatformFeePercent = 10.00m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RideShare.Core.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RiderId");

                    b.HasIndex("RideId", "PassengerId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RideId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex("RideId");

                    b.HasIndex("Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("ArrivalNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DestLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("DestLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Fare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("HelmetProvided")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("OriginLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("OriginLng")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartureTime");

                    b.HasIndex("RiderId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "DepartureTime");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("RideShare.Core.Entities.RideRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DropoffLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("DropoffLng")
                        .HasColumnType("double precision");

                    b.Property<string>("DropoffLocation")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PickupLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("PickupLng")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("text");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RideId");

                    b.HasIndex("Status");

                    b.HasIndex("RideId", "Status");

                    b.ToTable("RideRequests");
                });

            modelBuilder.Entity("RideShare.Core.Entities.RiderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsLicenseVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MotorcycleModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRides")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("VerifiedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VerifiedByAdminId");

                    b.ToTable("RiderProfiles");
                });

            modelBuilder.Entity("RideShare.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@rideshare.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$K0GyK.A0L1qJK8VuWJYQO.KJ8gPq4PKjX5l2V9hPJQZkKJ8kP0Wau",
                            Role = "Admin",
                            ThemePreference = "light"
                        });
                });

            modelBuilder.Entity("RideShare.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("RideShare.Core.Entities.Ride", "Ride")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("RideShare.Core.Entities.OnDemandRequest", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "AcceptedRider")
                        .WithMany()
                        .HasForeignKey("AcceptedRiderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RideShare.Core.Entities.User", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AcceptedRider");

                    b.Navigation("Passenger");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("RideShare.Core.Entities.PricingSettings", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Rating", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Ride");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Report", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.User", "ResolvedByAdmin")
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RideShare.Core.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Ride", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "Rider")
                        .WithMany("PostedRides")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("RideShare.Core.Entities.RideRequest", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "Passenger")
                        .WithMany("RideRequests")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.Ride", "Ride")
                        .WithMany("Requests")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("RideShare.Core.Entities.RiderProfile", b =>
                {
                    b.HasOne("RideShare.Core.Entities.User", "User")
                        .WithOne("RiderProfile")
                        .HasForeignKey("RideShare.Core.Entities.RiderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideShare.Core.Entities.User", "VerifiedByAdmin")
                        .WithMany()
                        .HasForeignKey("VerifiedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("RideShare.Core.Entities.Ride", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("RideShare.Core.Entities.User", b =>
                {
                    b.Navigation("PostedRides");

                    b.Navigation("RideRequests");

                    b.Navigation("RiderProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
